Update Declarative Link Capturing (DLC) proposal
WICG/sw-launch pull request #26
Opened 2021-01-08 06:58 UTC by mgiuca

- Rewrite introduction to give a better overview.
- Got rid of auto (just says that none is the default).
- Converted underscores (_) to dashes (-) in enum values.
- Accept either a string or a list.
- Removed some issues that are now resolved by the above changes.

2021-01-08 07:01 UTC, mgiuca commented
@alancutter PTAL

2021-01-21 06:24 UTC, alancutter requested changes

2021-01-21 06:24 UTC, alancutter commented on declarative_link_capturing.md
>  *   `existing_client_event` would push a new file handle to the `launchQueue` of the existing context before firing the `launch` event.
Update to have dashes.

2021-01-21 06:45 UTC, mgiuca commented on declarative_link_capturing.md
>  *   `existing_client_event` would push a new file handle to the `launchQueue` of the existing context before firing the `launch` event.
Done.

2021-01-22 01:28 UTC, merged